name: Scrap eshops & process

# Controls when the action will run.
on:
  workflow_run:
    workflows: ["Scrap valid NSUIDs"]
    types:
      - completed
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    # Grant GITHUB_TOKEN permissions to write to the repository
    permissions:
      contents: write

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up the newest Python 3 version
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Download titledb file
        run: |
          wget --tries=0 --retry-connrefused --wait=10 https://github.com/blawar/titledb/raw/refs/heads/master/US.en.json
          wget --tries=0 --retry-connrefused --wait=10 https://github.com/blawar/titledb/raw/refs/heads/master/BR.pt.json
          wget --tries=0 --retry-connrefused --wait=10 https://github.com/blawar/titledb/raw/refs/heads/master/CA.en.json
          wget --tries=0 --retry-connrefused --wait=10 https://github.com/blawar/titledb/raw/refs/heads/master/AR.es.json
          wget --tries=0 --retry-connrefused --wait=10 https://github.com/blawar/titledb/raw/refs/heads/master/CL.es.json
          wget --tries=0 --retry-connrefused --wait=10 https://github.com/blawar/titledb/raw/refs/heads/master/CO.es.json
          wget --tries=0 --retry-connrefused --wait=10 https://github.com/blawar/titledb/raw/refs/heads/master/PE.es.json
          wget --tries=0 --retry-connrefused --wait=10 https://github.com/blawar/titledb/raw/refs/heads/master/MX.es.json
          wget --tries=0 --retry-connrefused --wait=10 https://github.com/blawar/titledb/raw/refs/heads/master/HK.zh.json
          wget --tries=0 --retry-connrefused --wait=10 https://github.com/blawar/titledb/raw/refs/heads/master/AU.en.json
          wget --tries=0 --retry-connrefused --wait=10 https://github.com/blawar/titledb/raw/refs/heads/master/NZ.en.json
          wget --tries=0 --retry-connrefused --wait=10 https://github.com/blawar/titledb/raw/refs/heads/master/JP.ja.json

      - name: Download titledb_filtered
        run: |
          git clone --depth 1 https://github.com/masagrator/titledb_filtered.git
          git clone --depth 1 https://github.com/masagrator/version_dump.git
      
      # 5. Run your Python script
      - name: Install libraries
        run: |
          pip install requests

      - name: Run Python script
        run: |
          python -u extractdatajp.py
          python -u extractdatahk.py
          python -u extractdataus.py
          python -u extractdataeu.py
          python -u ProcessToTitleids.py
          python -u region_check.py

      # 6. Commit and push the files from the "output" folder
      - name: Push new files to repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add --ignore-removal scrap/
          git add --ignore-removal output/
          git commit -m "Update" || exit 0
          git push
